# Generated by Django 3.2.13 on 2023-03-16 16:38

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoEDivinationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('name', models.CharField(help_text='characters limit = 50', max_length=50, verbose_name='Name of the card')),
                ('description', models.TextField(help_text='characters limit = 200', max_length=200, verbose_name='Description of the card')),
                ('stack_size', models.IntegerField(help_text='insert an integer number only', verbose_name='Amount of cards required')),
                ('image', models.ImageField(blank=True, null=True, upload_to=cards.models.mock_name, verbose_name='Image of the divination card')),
                ('slug', models.SlugField(blank=True, help_text='no need to fill it', null=True, verbose_name='Dynamic url')),
            ],
            options={
                'verbose_name': 'PoE card',
                'verbose_name_plural': 'PoE cards',
            },
        ),
    ]
